spring:
  docker:
    compose:
      enabled: true
      file: finance-service/docker/docker-compose.yml
  jpa:
    show-sql: true
logging:
  level:
    root: INFO
    com.example.financeservice: INFO

custom:
  catalogue-service:
    url: http://localhost:8083/api/v1/outbox