spring:
  docker:
    compose:
      enabled: true
      file: task-service/docker-dev-build/docker-compose.yml
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/education_platform
            user-name-attribute: preferred

custom:
  file-service-url: http:/localhost:8082/api/v1/files

springdoc:
  swagger-ui:
    oauth:
      client-id: task-service-swagger-ui
      client-secret: cguk5MFIfES8KpbiFrvmeyBPsohB1Qcn