spring:
  docker:
    compose:
      enabled: true
      file: task-service/docker/docker-compose.yml
  security:
    oauth2:
      client:
        provider:
          keycloak:
            external-issuer-uri: http://localhost:8080/realms/education_platform
            issuer-uri: http://localhost:8080/realms/education_platform
            user-name-attribute: preferred

springdoc:
  swagger-ui:
    oauth:
      client-id: task-service-swagger-ui
      client-secret: cguk5MFIfES8KpbiFrvmeyBPsohB1Qcn

logging:
  level:
    org:
      apache:
        http: DEBUG

custom:
  file-service-url: http://localhost:8082/api/v1/files
