name: ep-dev-fs

services:
  psql:
    image: postgres:17-alpine
    env_file:
      - environment/db.env
    ports:
      - '5434:5432'
  minio:
    image: quay.io/minio/minio:latest
    env_file:
      - environment/s3.env
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'